import type { FoodMaker, MenuItem } from '@/types'

export const MOCK_MAKERS: FoodMaker[] = [
  {
    id: '1',
    user_id: 'u1',
    display_name: "Mama Adaeze's Kitchen",
    bio: 'Authentic Nigerian home cooking made with love. Jollof rice, egusi soup, and more.',
    avatar_url: null,
    banner_url: null,
    cuisine_tags: ['Nigerian', 'African', 'Halal'],
    avg_rating: 4.9,
    total_reviews: 128,
    is_open: true,
    service_radius_km: 5,
    lat: 40.7128,
    lng: -74.006,
    prep_time_mins: 35,
    distance_km: 0.8,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    user_id: 'u2',
    display_name: "Rosa's Mexican Cocina",
    bio: 'Traditional Mexican recipes from Oaxaca. Everything made fresh daily.',
    avatar_url: null,
    banner_url: null,
    cuisine_tags: ['Mexican', 'Vegan', 'Spicy'],
    avg_rating: 4.7,
    total_reviews: 94,
    is_open: true,
    service_radius_km: 4,
    lat: 40.714,
    lng: -74.009,
    prep_time_mins: 25,
    distance_km: 1.2,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    user_id: 'u3',
    display_name: "Priya's Tiffin Box",
    bio: 'Home-style Indian curries, dals, and fresh roti. Vegetarian-friendly.',
    avatar_url: null,
    banner_url: null,
    cuisine_tags: ['Indian', 'Vegetarian', 'Vegan'],
    avg_rating: 4.8,
    total_reviews: 211,
    is_open: false,
    service_radius_km: 6,
    lat: 40.715,
    lng: -74.002,
    prep_time_mins: 40,
    distance_km: 1.8,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    user_id: 'u4',
    display_name: "Miss Bonnie's Soul Food",
    bio: 'Southern comfort food that tastes just like grandma made it.',
    avatar_url: null,
    banner_url: null,
    cuisine_tags: ['Soul Food', 'Southern', 'American'],
    avg_rating: 4.95,
    total_reviews: 67,
    is_open: true,
    service_radius_km: 3,
    lat: 40.718,
    lng: -74.01,
    prep_time_mins: 45,
    distance_km: 2.1,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    user_id: 'u5',
    display_name: "Ming's Dim Sum",
    bio: 'Hand-made dumplings and bao fresh every morning. Limited quantities!',
    avatar_url: null,
    banner_url: null,
    cuisine_tags: ['Chinese', 'Asian'],
    avg_rating: 4.6,
    total_reviews: 183,
    is_open: true,
    service_radius_km: 5,
    lat: 40.711,
    lng: -74.005,
    prep_time_mins: 20,
    distance_km: 0.5,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    user_id: 'u6',
    display_name: "Aunty Pat's Caribbean",
    bio: 'Jamaican jerk chicken, oxtail, and rice & peas. Taste the islands!',
    avatar_url: null,
    banner_url: null,
    cuisine_tags: ['Caribbean', 'Jamaican', 'Spicy'],
    avg_rating: 4.85,
    total_reviews: 142,
    is_open: true,
    service_radius_km: 4,
    lat: 40.72,
    lng: -74.008,
    prep_time_mins: 50,
    distance_km: 2.4,
    created_at: new Date().toISOString(),
  },
]

const MAKER_EMOJIS: Record<string, string> = {
  '1': '🍲',
  '2': '🌮',
  '3': '🍛',
  '4': '🍗',
  '5': '🥟',
  '6': '🍖',
}

export const getMakerEmoji = (makerId: string) => MAKER_EMOJIS[makerId] ?? '🍽️'

export const MOCK_MENU_ITEMS: Record<string, MenuItem[]> = {
  '1': [
    {
      id: 'm1-1',
      maker_id: '1',
      name: 'Jollof Rice + Chicken',
      description: 'Party-style jollof rice with seasoned grilled chicken and fried plantain.',
      price: 18.00,
      photo_url: null,
      dietary_tags: ['halal'],
      is_available: true,
      daily_limit: 20,
      prep_time_mins: 35,
      category: 'Mains',
    },
    {
      id: 'm1-2',
      maker_id: '1',
      name: 'Egusi Soup + Fufu',
      description: 'Rich melon seed soup with assorted meats, served with freshly pounded fufu.',
      price: 22.00,
      photo_url: null,
      dietary_tags: ['halal'],
      is_available: true,
      daily_limit: 15,
      prep_time_mins: 40,
      category: 'Mains',
    },
    {
      id: 'm1-3',
      maker_id: '1',
      name: 'Puff Puff (6 pcs)',
      description: 'Freshly fried Nigerian doughnuts, light and airy with a hint of sweetness.',
      price: 6.00,
      photo_url: null,
      dietary_tags: ['vegan'],
      is_available: true,
      daily_limit: null,
      prep_time_mins: 10,
      category: 'Snacks',
    },
    {
      id: 'm1-4',
      maker_id: '1',
      name: 'Pepper Soup',
      description: 'Spicy and aromatic Nigerian pepper soup with goat meat.',
      price: 14.00,
      photo_url: null,
      dietary_tags: ['halal', 'spicy'],
      is_available: true,
      daily_limit: 10,
      prep_time_mins: 30,
      category: 'Soups',
    },
  ],
  '2': [
    {
      id: 'm2-1',
      maker_id: '2',
      name: 'Mole Negro Enchiladas',
      description: 'Handmade corn tortillas with pulled chicken in rich Oaxacan black mole.',
      price: 16.00,
      photo_url: null,
      dietary_tags: [],
      is_available: true,
      daily_limit: 12,
      prep_time_mins: 25,
      category: 'Mains',
    },
    {
      id: 'm2-2',
      maker_id: '2',
      name: 'Tamales (3 pcs)',
      description: 'Traditional masa tamales with pork verde filling, wrapped in corn husk.',
      price: 12.00,
      photo_url: null,
      dietary_tags: [],
      is_available: true,
      daily_limit: 20,
      prep_time_mins: 15,
      category: 'Mains',
    },
    {
      id: 'm2-3',
      maker_id: '2',
      name: 'Vegan Tlayuda',
      description: 'Crispy tortilla with black beans, avocado, chapulines, and salsa.',
      price: 13.00,
      photo_url: null,
      dietary_tags: ['vegan'],
      is_available: true,
      daily_limit: null,
      prep_time_mins: 20,
      category: 'Mains',
    },
  ],
  '4': [
    {
      id: 'm4-1',
      maker_id: '4',
      name: 'Fried Chicken & Waffles',
      description: 'Crispy Southern fried chicken on fluffy buttermilk waffles with maple syrup.',
      price: 19.00,
      photo_url: null,
      dietary_tags: [],
      is_available: true,
      daily_limit: 15,
      prep_time_mins: 45,
      category: 'Mains',
    },
    {
      id: 'm4-2',
      maker_id: '4',
      name: 'Mac & Cheese (lg)',
      description: 'Baked 4-cheese mac loaded with breadcrumbs. Pure comfort.',
      price: 11.00,
      photo_url: null,
      dietary_tags: [],
      is_available: true,
      daily_limit: null,
      prep_time_mins: 20,
      category: 'Sides',
    },
    {
      id: 'm4-3',
      maker_id: '4',
      name: 'Oxtail Stew',
      description: 'Slow-braised oxtail with butter beans, carrots, and herbs. Served with rice.',
      price: 24.00,
      photo_url: null,
      dietary_tags: [],
      is_available: true,
      daily_limit: 8,
      prep_time_mins: 45,
      category: 'Mains',
    },
  ],
  '5': [
    {
      id: 'm5-1',
      maker_id: '5',
      name: 'Pork Dumplings (8 pcs)',
      description: 'Juicy hand-folded pork & ginger dumplings, steamed or pan-fried.',
      price: 13.00,
      photo_url: null,
      dietary_tags: [],
      is_available: true,
      daily_limit: 30,
      prep_time_mins: 20,
      category: 'Dim Sum',
    },
    {
      id: 'm5-2',
      maker_id: '5',
      name: 'BBQ Pork Bao (3 pcs)',
      description: 'Fluffy steamed buns filled with sweet char siu pork.',
      price: 10.00,
      photo_url: null,
      dietary_tags: [],
      is_available: true,
      daily_limit: 25,
      prep_time_mins: 15,
      category: 'Bao',
    },
    {
      id: 'm5-3',
      maker_id: '5',
      name: 'Vegetable Har Gow (6 pcs)',
      description: 'Crystal-wrapped translucent dumplings with mixed vegetables.',
      price: 11.00,
      photo_url: null,
      dietary_tags: ['vegan'],
      is_available: true,
      daily_limit: 20,
      prep_time_mins: 20,
      category: 'Dim Sum',
    },
  ],
}

// Fill in empty makers with some items
for (const makerId of ['3', '6']) {
  MOCK_MENU_ITEMS[makerId] = [
    {
      id: `m${makerId}-1`,
      maker_id: makerId,
      name: 'Signature Dish',
      description: 'Our most popular item, made fresh daily with the finest ingredients.',
      price: 16.00,
      photo_url: null,
      dietary_tags: [],
      is_available: true,
      daily_limit: 15,
      prep_time_mins: 30,
      category: 'Mains',
    },
  ]
}
