-- ────────────────────────────────────────────────────────────────────────────
-- Migration 026: Performance Indexes & Additional Security Hardening
-- Generated by production audit — Apr 2026
--
-- Adds missing composite indexes for the most common query patterns across
-- the four apps, and tightens a few remaining RLS gaps.
-- All indexes are created CONCURRENTLY where possible (safe for live DBs).
-- ────────────────────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────────────────────
-- 1. ORDERS — most queried table across all apps
-- ────────────────────────────────────────────────────────────────────────────

-- Customer dashboard: "my orders, newest first"
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_customer_created
  ON public.orders (customer_id, created_at DESC);

-- Maker dashboard: "orders for my kitchen by status"
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_maker_status
  ON public.orders (maker_id, status);

-- Driver dashboard: "orders assigned to me by status"
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_nexter_status
  ON public.orders (nexter_id, status);

-- Admin analytics: "orders by status and time range"
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_status_created
  ON public.orders (status, created_at DESC);

-- Stripe webhook idempotency lookup: "find order by payment intent"
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_stripe_payment_intent
  ON public.orders (stripe_payment_intent_id)
  WHERE stripe_payment_intent_id IS NOT NULL;

-- ────────────────────────────────────────────────────────────────────────────
-- 2. NOTIFICATIONS — polled frequently by all apps
-- ────────────────────────────────────────────────────────────────────────────

-- "My unread notifications, newest first" (the most common query)
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_notifications_user_unread
  ON public.notifications (user_id, created_at DESC)
  WHERE is_read = false;

-- ────────────────────────────────────────────────────────────────────────────
-- 3. DRIVER PROFILES — used in driver-matching and online-status queries
-- ────────────────────────────────────────────────────────────────────────────

-- "Find all active/online drivers" (used when broadcasting new-order notifications)
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_driver_profiles_active
  ON public.driver_profiles (is_active)
  WHERE is_active = true;

-- ────────────────────────────────────────────────────────────────────────────
-- 4. NEXTER LOCATIONS — used for proximity-based driver matching
-- ────────────────────────────────────────────────────────────────────────────

-- "Latest location per driver" (used in haversine distance queries)
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_nexter_locations_nexter_updated
  ON public.nexter_locations (nexter_id, updated_at DESC);

-- ────────────────────────────────────────────────────────────────────────────
-- 5. WITHDRAWALS — used in driver balance calculations
-- ────────────────────────────────────────────────────────────────────────────

-- "All non-rejected withdrawals for a driver" (used in balance check)
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_withdrawals_user_status
  ON public.withdrawals (user_id, status);

-- ────────────────────────────────────────────────────────────────────────────
-- 6. SUPPORT TICKETS — used in admin support queue
-- ────────────────────────────────────────────────────────────────────────────

-- "Open tickets by priority, newest first"
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_support_tickets_status_priority
  ON public.support_tickets (status, priority, created_at DESC);

-- ────────────────────────────────────────────────────────────────────────────
-- 7. ADMIN AUDIT LOG — used in admin audit trail queries
-- ────────────────────────────────────────────────────────────────────────────

-- "Audit log by target (e.g., all events for order X)"
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_admin_audit_log_target
  ON public.admin_audit_log (target_type, target_id, created_at DESC);

-- ────────────────────────────────────────────────────────────────────────────
-- 8. SECURITY: Ensure withdrawals RLS is enabled
-- Drivers should only see their own withdrawal records.
-- ────────────────────────────────────────────────────────────────────────────

ALTER TABLE IF EXISTS public.withdrawals ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'withdrawals'
      AND policyname = 'Users can view own withdrawals'
  ) THEN
    CREATE POLICY "Users can view own withdrawals"
      ON public.withdrawals
      FOR SELECT
      USING (auth.uid() = user_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'withdrawals'
      AND policyname = 'Users can insert own withdrawals'
  ) THEN
    CREATE POLICY "Users can insert own withdrawals"
      ON public.withdrawals
      FOR INSERT
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────────────────
-- 9. SECURITY: Ensure nexter_locations RLS is enabled
-- Drivers should only be able to write their own location.
-- ────────────────────────────────────────────────────────────────────────────

ALTER TABLE IF EXISTS public.nexter_locations ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'nexter_locations'
      AND policyname = 'Drivers can upsert own location'
  ) THEN
    CREATE POLICY "Drivers can upsert own location"
      ON public.nexter_locations
      FOR ALL
      USING (auth.uid() = nexter_id)
      WITH CHECK (auth.uid() = nexter_id);
  END IF;
END $$;
