-- ============================================================
-- 054: DoorDash-style order stacking / multi-stop routing
--
-- New additions:
--   driver_route_plans  — ordered stop list for a multi-stop run
--   order_stack_offers  — pending stack offers pushed to active drivers
--   settings rows       — stack_bonus_amount, stack_limit
--   idx_orders_stacking — compound index for fast stack-candidate lookup
--   accept_order_atomic — atomic single/stack accept with bonus
--   release_stack_offer — expires or cancels a pending stack offer
-- ============================================================

-- ── 1. driver_route_plans ─────────────────────────────────────────────────────
-- Stores the optimised stop sequence for a multi-stop run.
-- stops is an ordered JSONB array of:
--   {
--     "seq":      number,          -- 1-based position in route
--     "type":     "pickup"|"dropoff",
--     "order_id": "uuid",
--     "lat":      number,
--     "lng":      number,
--     "label":    "string",        -- maker name (pickup) or street (dropoff)
--     "done":     boolean
--   }

CREATE TABLE IF NOT EXISTS public.driver_route_plans (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id       uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  order_group_id  uuid        NOT NULL,
  stops           jsonb       NOT NULL DEFAULT '[]',
  total_distance_km numeric(8,3),         -- sum of all legs
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_driver_route_plans_driver
  ON public.driver_route_plans (driver_id)
  WHERE stops != '[]'::jsonb;

CREATE INDEX IF NOT EXISTS idx_driver_route_plans_group
  ON public.driver_route_plans (order_group_id);

ALTER TABLE public.driver_route_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Drivers manage own route plans"
  ON public.driver_route_plans
  USING (auth.uid() = driver_id);

-- ── 2. order_stack_offers ─────────────────────────────────────────────────────
-- When a driver is already mid-delivery, the system can push a compatible
-- nearby order as a "stack offer".  Driver has stack_offer_timeout_secs to
-- accept or decline before it expires.

CREATE TABLE IF NOT EXISTS public.order_stack_offers (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id   uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  order_id    uuid        NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  score       numeric(6,3),               -- compatibility score (higher = better fit)
  status      text        NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending','accepted','rejected','expired')),
  expires_at  timestamptz NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (driver_id, order_id)
);

CREATE INDEX IF NOT EXISTS idx_stack_offers_driver_pending
  ON public.order_stack_offers (driver_id, status, expires_at)
  WHERE status = 'pending';

ALTER TABLE public.order_stack_offers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Drivers read own stack offers"
  ON public.order_stack_offers FOR SELECT
  USING (auth.uid() = driver_id);

-- ── 3. Stack-related settings ─────────────────────────────────────────────────
INSERT INTO public.settings (key, value) VALUES
  ('stack_limit',               '2'),      -- max orders a driver can carry at once
  ('stack_bonus_amount',        '1.50'),   -- $ added to driver_payout for each stacked order
  ('stack_pickup_radius_km',    '3.0'),    -- max km between two pickup locations
  ('stack_dropoff_radius_km',   '4.0'),    -- max km between two dropoff locations
  ('stack_detour_pct',          '40'),     -- max % route-length increase allowed
  ('stack_offer_timeout_secs',  '45')      -- seconds driver has to accept a stack offer
ON CONFLICT (key) DO NOTHING;

-- ── 4. Fast compound index for stack-candidate queries ────────────────────────
-- Finds unassigned preparing/ready orders quickly when checking for stacking.
CREATE INDEX IF NOT EXISTS idx_orders_stack_candidates
  ON public.orders (status, created_at)
  WHERE nexter_id IS NULL AND status IN ('preparing', 'ready');

-- ── 5. RPC: accept_order_atomic ───────────────────────────────────────────────
-- Atomically accepts a single order OR a stacked pair under one transaction.
-- Called by the Next.js accept-order API route (service role).
--
-- Parameters:
--   p_driver_id      — driver's auth.users.id
--   p_order_id       — the order being accepted now
--   p_pickup_pin     — 4-char PIN generated by API
--   p_group_id       — UUID to use for order_group_id (NULL → single order)
--   p_existing_ids   — existing order IDs in the group (NULL or empty → single order)
--   p_bonus_amount   — stack bonus to add to driver_payout (0 if single)
--
-- Returns:
--   'ok'             — accepted successfully
--   'taken'          — another driver beat us to it (race)
--   'bad_state'      — order not in accepting state

CREATE OR REPLACE FUNCTION public.accept_order_atomic(
  p_driver_id    uuid,
  p_order_id     uuid,
  p_pickup_pin   text,
  p_group_id     uuid    DEFAULT NULL,
  p_existing_ids uuid[]  DEFAULT NULL,
  p_bonus_amount numeric DEFAULT 0
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count  int;
BEGIN
  -- Accept the new order atomically
  UPDATE orders
  SET
    nexter_id        = p_driver_id,
    status           = 'driver_assigned',
    pickup_pin       = p_pickup_pin,
    pin_attempts     = 0,
    order_group_id   = COALESCE(p_group_id, NULL),
    driver_payout    = driver_payout + p_bonus_amount,
    updated_at       = now()
  WHERE
    id           = p_order_id
    AND status   IN ('preparing', 'ready')
    AND nexter_id IS NULL;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  IF v_count = 0 THEN
    RETURN 'taken';
  END IF;

  -- If stacking, stamp the group ID onto existing orders too
  IF p_group_id IS NOT NULL AND p_existing_ids IS NOT NULL AND array_length(p_existing_ids, 1) > 0 THEN
    UPDATE orders
    SET order_group_id = p_group_id,
        updated_at     = now()
    WHERE id = ANY(p_existing_ids)
      AND nexter_id = p_driver_id;
  END IF;

  RETURN 'ok';
END;
$$;

REVOKE EXECUTE ON FUNCTION public.accept_order_atomic(uuid, uuid, text, uuid, uuid[], numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.accept_order_atomic(uuid, uuid, text, uuid, uuid[], numeric) FROM authenticated;
-- Only the service role (Next.js API) may call this

-- ── 6. RPC: mark_route_stop_done ──────────────────────────────────────────────
-- Updates a single stop's "done" flag in the driver_route_plans.stops JSONB array.
-- Returns the updated stops array.

CREATE OR REPLACE FUNCTION public.mark_route_stop_done(
  p_driver_id    uuid,
  p_order_id     uuid,
  p_stop_type    text   -- 'pickup' or 'dropoff'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_stops    jsonb;
  v_new_stops jsonb;
  v_stop     jsonb;
  v_idx      int;
BEGIN
  SELECT stops INTO v_stops
  FROM driver_route_plans
  WHERE driver_id = p_driver_id
  ORDER BY created_at DESC
  LIMIT 1;

  IF v_stops IS NULL THEN
    RETURN '[]'::jsonb;
  END IF;

  -- Rebuild array with the matched stop marked done
  v_new_stops := '[]'::jsonb;
  FOR v_idx IN 0 .. jsonb_array_length(v_stops) - 1 LOOP
    v_stop := v_stops -> v_idx;
    IF (v_stop->>'order_id') = p_order_id::text
       AND (v_stop->>'type') = p_stop_type
    THEN
      v_stop := v_stop || '{"done":true}'::jsonb;
    END IF;
    v_new_stops := v_new_stops || jsonb_build_array(v_stop);
  END LOOP;

  UPDATE driver_route_plans
  SET stops = v_new_stops, updated_at = now()
  WHERE driver_id = p_driver_id
    AND stops @> jsonb_build_array(jsonb_build_object('order_id', p_order_id, 'type', p_stop_type));

  RETURN v_new_stops;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.mark_route_stop_done(uuid, uuid, text) FROM PUBLIC;
